#!/bin/bash

DIR="`dirname \"$0\"`" 
DIR="`( cd \"$DIR\" && readlink -f $(pwd) )`"
echo "DIR: $DIR"
export APPDIR=$DIR

export PYTHONHOME=$DIR/usr/
export PATH=$DIR/usr/bin:$PATH

source "$APPDIR/apprun-helper.sh"
save_environment
make_temp_libdir
link_libraries
echo "AILIBDIR=$AILIBDIR"

init_environment

fix_libxcb_dri3
fix_stdlibcxx
#fix_fontconfig
fix_library "libfontconfig"
fix_library "libfreetype"

export APPDIRS=$AILIBDIR:$APPDIRS

init_gtk

#export XDG_CONFIG_DIRS=$DIR/usr/share:$XDG_CONFIG_DIRS
export XDG_DATA_DIRS=$DIR/usr/share:$XDG_DATA_DIRS:/usr/local/share:/usr/share
export GI_TYPELIB_PATH=$DIR/usr/lib/girepository-1.0

if [ -e /etc/fonts/fonts.conf ]; then
  export FONTCONFIG_PATH=/etc/fonts
fi

run_hooks

python $DIR/usr/bin/mypaint "$@"

rm -rf "$AILIBDIR"
