#!/bin/bash

MYPAINT_ENV_CLEAN="$(env)"
export MYPAINT_ENV_CLEAN

DIR="$(readlink -f "$(dirname "$0")")"
echo "DIR: $DIR"
# The name of this variable is significant - it is used by the patched
# mypaint startup script to strip out non-appimage module search paths.
export APPDIR=$DIR


# Set up environment
export PYTHONHOME=$DIR/usr/
export PATH="$APPDIR/usr/bin:${PATH}:/sbin:/usr/sbin"
export LD_LIBRARY_PATH="$APPDIR/usr/lib:/usr/lib:$LD_LIBRARY_PATH"
export GCONV_PATH="${APPDIR}/usr/lib/gconv"

# Prevent gio modules being loaded from the host system
export GIO_MODULE_DIR=$DIR

# Set up gdkpixbuf vars
export GDK_PIXBUF_MODULEDIR="${APPDIR}/usr/lib/gdk-pixbuf-2.0/loaders"
export GDK_PIXBUF_MODULE_FILE="${APPDIR}/usr/lib/gdk-pixbuf-2.0/loaders.cache"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$GDK_PIXBUF_MODULEDIR"

# Set up user data locations and GObject introspection
export XDG_DATA_DIRS=$DIR/usr/share:$XDG_DATA_DIRS:/usr/local/share:/usr/share
export GI_TYPELIB_PATH=$DIR/usr/lib/girepository-1.0

if [ -e /etc/fonts/fonts.conf ]; then
  export FONTCONFIG_PATH=/etc/fonts
fi

# Set Adwaita theme explicitly, but allow it to be overridden
# by setting GTK_THEME when starting the appimage, in which
# case it is up to the user to set light or dark themes directly.
#
# Setting the theme explicitly avoids css-compatibility
# problems with older gtk3 versions on the host systems.
if [ -z "$GTK_THEME" ]; then
    echo "No explicit user theme set"
    # Helper returns 0 for dark theme, 1 for ordinary theme.
    # Set the path to let it find the required mypaint libs.
    PP="$APPDIR/usr/lib/mypaint/:$PYTHONPATH"
    if PYTHONPATH="$PP" python "$APPDIR/gtk-theme-helper.py" "$@"; then
	export GTK_THEME="Adwaita:dark"
    else
	export GTK_THEME="Adwaita"
    fi
else
    echo "GTK_THEME already set explicitly, we respect that."
fi

# Set GTK_LOCALEDIR so our patched version of libgtk can
# pick up the bundled .mo files
export GTK_LOCALEDIR=$APPDIR/usr/share/locale

python "$DIR/usr/bin/mypaint" "$@"
EXIT_CODE=$?

exit $EXIT_CODE
